export interface TraceMethodAugmentation {
    code: string;
    addedMethodCount: number;
}

export interface TraceFileAugmentation extends TraceMethodAugmentation {
    addedClassName?: string;
}

/**
 * Model-authored tests may add scenarios, but never replace a safe execution
 * baseline.  Deterministic Tier 1 already consists of those methods, so
 * appending it again would be redundant; every LLM-authored Tier preserves it.
 */
export function shouldPreserveVerifiedTrace(
    tier: number,
    tier1GenerationMode?: 'llm-evidence-bound' | 'deterministic-fallback'
): boolean {
    return tier > 1 || (tier === 1 && tier1GenerationMode === 'llm-evidence-bound');
}

function traceMethodName(method: string): string | undefined {
    return method.match(/^\s*def\s+(test_trace_case_\d+)\s*\(/m)?.[1];
}

/**
 * Add deterministic Trace methods to the existing unittest class without
 * rewriting any model-authored methods. The caller supplies already-indented
 * unittest methods; this module only chooses a safe insertion point before
 * the next top-level statement.
 */
export function appendTraceMethodsToUnittestClass(
    code: string,
    methods: string[]
): TraceMethodAugmentation {
    const renamed = methods.map(method => method.replace(
        /^(\s*)def\s+test_case_(\d+)\s*\(/m,
        '$1def test_trace_case_$2('
    ));
    const existingNames = new Set(
        [...code.matchAll(/^\s*def\s+(test_trace_case_\d+)\s*\(/gm)].map(match => match[1])
    );
    const missing = renamed.filter(method => {
        const name = traceMethodName(method);
        return Boolean(name && !existingNames.has(name));
    });
    if (missing.length === 0) {
        return { code, addedMethodCount: 0 };
    }

    const lines = code.split(/\r?\n/);
    const classIndex = lines.findIndex(line =>
        /^class\s+\w+\s*\(\s*(?:unittest\.)?(?:TestCase|IsolatedAsyncioTestCase)\s*\)\s*:$/.test(line)
    );
    if (classIndex < 0) {
        return { code, addedMethodCount: 0 };
    }

    let insertAt = lines.length;
    for (let index = classIndex + 1; index < lines.length; index++) {
        const line = lines[index];
        if (line.trim() && !/^\s/.test(line) && !line.trimStart().startsWith('#')) {
            insertAt = index;
            break;
        }
    }
    const separator = insertAt > classIndex + 1 && lines[insertAt - 1].trim() ? ['', ''] : [''];
    lines.splice(insertAt, 0, ...separator, ...missing, '');
    return { code: lines.join('\n'), addedMethodCount: missing.length };
}

/**
 * Preserve a verified class/property trace as its own TestCase. Merging its
 * methods into a model-authored class would risk overwriting an unrelated
 * setUp(), so this deliberately keeps a separate constructor and class scope.
 * The supplied file is generated by tier1TestFileBuilder, not model output.
 */
export function appendVerifiedTraceTestFile(
    code: string,
    deterministicFile: string,
    methodCount: number,
    targetName: string
): TraceFileAugmentation {
    const sourceLines = deterministicFile.split(/\r?\n/);
    const classIndex = sourceLines.findIndex(line => /^class\s+TestTier1\w*\s*\(/.test(line));
    if (classIndex < 0 || methodCount <= 0) {
        return { code, addedMethodCount: 0 };
    }
    const mainIndex = sourceLines.findIndex((line, index) =>
        index > classIndex && /^if __name__ == ['"]__main__['"]:/.test(line)
    );
    const deterministicImports = sourceLines
        .slice(0, classIndex)
        .filter(line => /^(?:from\s+\S+\s+import\s+|import\s+)/.test(line))
        .filter(line => line !== 'import unittest');
    const classBlock = sourceLines.slice(classIndex, mainIndex >= 0 ? mainIndex : sourceLines.length);
    const safeTargetName = targetName.replace(/\W+/g, '_') || 'target';
    let ordinal = 1;
    let className = `TestVerifiedTrace_${safeTargetName}`;
    while (new RegExp(`^class\\s+${className}\\s*\\(`, 'm').test(code)) {
        ordinal++;
        className = `TestVerifiedTrace_${safeTargetName}_${ordinal}`;
    }
    classBlock[0] = classBlock[0].replace(/^class\s+TestTier1\w*/, `class ${className}`);

    const missingImports = deterministicImports.filter(importLine => !code.split(/\r?\n/).includes(importLine));
    let augmented = code;
    if (missingImports.length > 0) {
        const codeLines = code.split(/\r?\n/);
        let futureEndIndex = -1;
        let inFutureParen = false;
        for (let i = 0; i < codeLines.length; i++) {
            const line = codeLines[i];
            if (/^\s*from\s+__future__\s+import\b/.test(line)) {
                futureEndIndex = i;
                if (line.includes('(') && !line.includes(')')) {
                    inFutureParen = true;
                }
            } else if (inFutureParen) {
                futureEndIndex = i;
                if (line.includes(')')) {
                    inFutureParen = false;
                }
            }
        }
        if (futureEndIndex >= 0) {
            codeLines.splice(futureEndIndex + 1, 0, ...missingImports);
            augmented = codeLines.join('\n');
        } else {
            augmented = `${missingImports.join('\n')}\n${code}`;
        }
    }
    const lines = augmented.split(/\r?\n/);
    const mainLine = lines.findIndex(line => /^if __name__ == ['"]__main__['"]:/.test(line));
    const insertAt = mainLine >= 0 ? mainLine : lines.length;
    const separator = insertAt > 0 && lines[insertAt - 1].trim() ? ['', ''] : [''];
    lines.splice(insertAt, 0, ...separator, '# Verified behavior-observation tests (not model-authored)', ...classBlock, '');
    return { code: lines.join('\n'), addedMethodCount: methodCount, addedClassName: className };
}

/** Restore runner-owned Trace classes after every model repair, outside its fixtures. */
export function restoreVerifiedTraceTestFile(
    code: string, deterministicFile: string, methodCount: number, targetName: string
): TraceFileAugmentation {
    const prefix = `TestVerifiedTrace_${targetName.replace(/\W+/g, '_') || 'target'}`;
    const lines = code.split(/\r?\n/);
    for (let index = lines.length - 1; index >= 0; index--) {
        if (!new RegExp(`^class\\s+${prefix}(?:_\\d+)?\\s*\\(`).test(lines[index])) { continue; }
        let end = index + 1;
        while (end < lines.length && (!lines[end].trim() || /^\s/.test(lines[end]) || /^#/.test(lines[end]))) { end++; }
        let start = index;
        while (start > 0 && /^@/.test(lines[start - 1])) { start--; }
        if (start > 0 && lines[start - 1] === '# Verified behavior-observation tests (not model-authored)') { start--; }
        while (start > 0 && !lines[start - 1].trim()) { start--; }
        lines.splice(start, end - start);
    }
    const restored = appendVerifiedTraceTestFile(lines.join('\n').trim(), deterministicFile, methodCount, targetName);
    return { ...restored, code: restored.code.trim() + '\n' };
}
